### ISSUE TITLE
Use "brand" fonts in title

### ISSUE THREAD

**Issue by raae** [queen-raae/datainthewild.fm#1]
- Use the boldest var(--neo-Grotesque) for DATA and primary color for DATA
- Use apricot for the "in the wild"
- Set the title to "Data <span>in the wild</span>" and style the h1 span to apricot

![Data in the Wild - new design](https://github.com/queen-raae/datainthewild.fm/assets/478531/da75d49e-0c90-4a4c-8157-6bb47b95a2a8)

**Comment by raae** [comment]
[Archive.zip](https://github.com/queen-raae/datainthewild.fm/files/14787453/Archive.zip)

**Comment by rishi-raj-jain** [comment]
Damn!

https://github.com/queen-raae/datainthewild.fm/commit/6a0856206ec15af2b61f04c1e40c5fc6ccb8cca3 got directly committed 😅

I'll make sure to create PRs in the future.

But it does all of what was listed in the tasks.

Please take a look?

**Comment by rishi-raj-jain** [comment]
The commit does the following apart from what was asked in the tasks:

- `Inter` was not loaded earlier. It's now referenced over https://github.com/queen-raae/datainthewild.fm/blob/main/src/components/Font.astro#L35 and taken care of loading with fallback font using `astro-font`
- Adds types for `node` to have autocompletions (and less noise) while using node internals.

**Comment by rishi-raj-jain** [comment]
Ah it reflected on https://datainthewild.fm/ superbly 👇🏻

<img width="1005" alt="Screenshot 2024-03-28 at 5 43 25 PM" src="https://github.com/queen-raae/datainthewild.fm/assets/46300090/90104d04-0ff0-433b-8e8d-466629f64234">

**Comment by raae** [comment]
I'd rather not do utility classes in this project (mainly to see how it feels). So, if you could change it to be defined in the global CSS as "h1 span" for apricot and `em` for the brand color, that would be great.

What do you mean Inter was not loaded, using the Modern Font Stacks https://github.com/system-fonts/modern-font-stacks#neo-grotesque, so it should use one of the fonts in th e?

**Comment by raae** [comment]
My bad with the instruction on the title should have been `<em>Data</em> <span>in the wild</span>`

**Comment by rishi-raj-jain** [comment]
@raae 

- No worries, created https://github.com/queen-raae/datainthewild.fm/pull/4
- Ah I see it. It's a learning for me. I thought Inter is not part of every browser.
