### ISSUE TITLE
Optimize images

### ISSUE THREAD

**Issue by raae** [queen-raae/datainthewild.fm#3]
In component "Reel":
- Use Astro image or other methods so the images are not 1 MB each. 
- Make sure the images are still responsive as they are now.
- Add background color of var(--paper) so the border does not show through while loading

Background images:
- Could this approach be user https://docs.astro.build/en/guides/images/#generating-images-with-getimage, but in the style section instead of in an inline stye?

**Comment by rishi-raj-jain** [comment]
Let's get to this with #1 done?

**Comment by raae** [comment]
You can start on it in a separate PR.
